server:
  port: 8082

spring:
  profiles:
    active: sit
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8
    username: root
    password: mgl
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
mybatis:
  type-aliases-package: com.github.mgljava.domain
  mapper-locations: classpath:mapper/*.xml
